# Default values for Go projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: draft
  tag: dev
  pullPolicy: IfNotPresent

# define environment variables here as a map of key: value
env:

service:
  type: ClusterIP
  externalPort: 5678
  internalPort: 5678
  annotations:
    # fabric8.io/expose: "true"
    # fabric8.io/ingress.annotations: |-
    #   kubernetes.io/ingress.class: nginx
    #   nginx.ingress.kubernetes.io/backend-protocol: GRPC
    #   nginx.ingress.kubernetes.io/auth-url: https://auth.jenkins-x1.iviet.com/oauth2/auth
    #   nginx.ingress.kubernetes.io/auth-signin: https://auth.jenkins-x1.iviet.com/oauth2/start?rd=https%3A%2F%2F$http_host$escaped_request_uri

nodeSelector:
  gpu-manager: enabled
podAnnotations:
  reloader.stakater.com/auto: "true"
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 80m
    memory: 128Mi
probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  initialDelaySeconds: 20
  failureThreshold: 1
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

nvidia:
  # stuffs installed by nvidia-driver-installer that we want to transfer
  origin:
    binaries:
    - nvidia-cuda-mps-control
    - nvidia-cuda-mps-server
    - nvidia-debugdump
    - nvidia-persistenced
    - nvidia-smi
    libraries:
    - libnvidia-ml.so
    - libcuda.so
    - libnvidia-ptxjitcompiler.so
    - libnvidia-fatbinaryloader.so
    - libnvidia-opencl.so
    - libnvidia-compiler.so
    - libvdpau_nvidia.so
    - libnvidia-encode.so
    - libnvcuvid.so
    - libnvidia-fbc.so
    - libnvidia-ifr.so
    - libGL.so
    - libGLX.so
    - libOpenGL.so
    - libGLESv1_CM.so
    - libGLESv2.so
    - libEGL.so
    - libGLdispatch.so
    - libGLX_nvidia.so
    - libEGL_nvidia.so
    - libGLESv2_nvidia.so
    - libGLESv1_CM_nvidia.so
    - libnvidia-eglcore.so
    - libnvidia-egl-wayland.so
    - libnvidia-glcore.so
    - libnvidia-tls.so
    - libnvidia-glsi.so
    - libnvidia-opticalflow.so
  # stuffs in our container that we want to transfer too
  extra:
    binaries:
    - gpu-client
    libraries:
    - libcuda-control.so
