apiVersion: v1
kind: Pod
metadata:
  name: tensorflow1
  namespace: test
spec:
  schedulerName: gpu-scheduler
  nodeSelector:
    nvidia-device-enable: enable
  tolerations:
  - key: nvidia.com/gpu
    operator: Equal
    value: present
    effect: NoSchedule
  containers:
  - name: tensorflow
    image: tensorflow/tensorflow:2.2.0rc3-gpu
    command:
    - sleep
    - "10000"
    env:
    - name: LOGGER_LEVEL
      value: "8"
    resources:
      requests:
        cpu: 700m
        memory: 2Gi
        tencent.com/vcuda-core: 20
        tencent.com/vcuda-memory: 10
      limits:
        cpu: 700m
        memory: 2Gi
        tencent.com/vcuda-core: 20
        tencent.com/vcuda-memory: 10
