apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-manager-config
data:
  volume.conf: |-
    {
      "volume": [
      {{- $binaries := list }}
      {{- if .Values.nvidia.extra.binaries }}
        {{- range $index, $binary := .Values.nvidia.extra.binaries }}
          {{- $binaries = append $binaries $binary }}
        {{- end }}
      {{- end }}
      {{- range $index, $binary := .Values.nvidia.origin.binaries }}
        {{- $binaries = append $binaries $binary }}
      {{- end }}
      {{- $libraries := list }}
      {{- if .Values.nvidia.extra.libraries }}
        {{- range $index, $library := .Values.nvidia.extra.libraries }}
          {{- $libraries = append $libraries $library }}
        {{- end }}
      {{- end }}
      {{- range $index, $library := .Values.nvidia.origin.libraries }}
        {{- $libraries = append $libraries $library }}
      {{- end }}
        {
          "name": "nvidia",
          "base": "/home/kubernetes/bin/gpu-manager/vdriver",
          "mode": "ro",
          "components": {
            "binaries": {{ $binaries | toPrettyJson | indent 12 | trim }},
            "libraries": {{ $libraries | toPrettyJson | indent 12 | trim }}
          }
        },
        {
          "name": "origin",
          "base": "/home/kubernetes/bin/gpu-manager/vdriver",
          "mode": "ro",
          "components": {
            "binaries": {{ .Values.nvidia.origin.binaries | toPrettyJson | indent 12 | trim }},
            "libraries": {{ .Values.nvidia.origin.libraries | toPrettyJson | indent 12 | trim }}
          }
        }
      ]
    }
{{- if .Values.config }}
  extra-config.json: {{ .Values.config | toJson | quote }}
{{- else }}
  extra-config.json: "{}"
{{- end }}
