apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-manager-config
data:
  volume.conf: |-
    {
      "volume": [
        {
          "name": "nvidia",
          "base": "/etc/gpu-manager/vdriver",
          "mode": "ro",
          "components": {
            "binaries": [
              "nvidia-cuda-mps-control",
              "nvidia-cuda-mps-server",
              "nvidia-debugdump",
              "nvidia-persistenced",
              "nvidia-smi",
              "gpu-client"
            ],
            "libraries": [
              "libnvidia-ml.so",
              "libcuda.so",
              "libcuda-control.so",
              "libnvidia-ptxjitcompiler.so",
              "libnvidia-fatbinaryloader.so",
              "libnvidia-opencl.so",
              "libnvidia-compiler.so",
              "libvdpau_nvidia.so",
              "libnvidia-encode.so",
              "libnvcuvid.so",
              "libnvidia-fbc.so",
              "libnvidia-ifr.so",
              "libGL.so",
              "libGLX.so",
              "libOpenGL.so",
              "libGLESv1_CM.so",
              "libGLESv2.so",
              "libEGL.so",
              "libGLdispatch.so",
              "libGLX_nvidia.so",
              "libEGL_nvidia.so",
              "libGLESv2_nvidia.so",
              "libGLESv1_CM_nvidia.so",
              "libnvidia-eglcore.so",
              "libnvidia-egl-wayland.so",
              "libnvidia-glcore.so",
              "libnvidia-tls.so",
              "libnvidia-glsi.so",
              "libnvidia-opticalflow.so"
            ]
          }
        },
        {
          "name": "origin",
          "base": "/etc/gpu-manager/vdriver",
          "mode": "ro",
          "components": {
            "binaries": [
              "nvidia-cuda-mps-control",
              "nvidia-cuda-mps-server",
              "nvidia-debugdump",
              "nvidia-persistenced",
              "nvidia-smi"
            ],
            "libraries": [
              "libnvidia-ml.so",
              "libcuda.so",
              "libnvidia-ptxjitcompiler.so",
              "libnvidia-fatbinaryloader.so",
              "libnvidia-opencl.so",
              "libnvidia-compiler.so",
              "libvdpau_nvidia.so",
              "libnvidia-encode.so",
              "libnvcuvid.so",
              "libnvidia-fbc.so",
              "libnvidia-ifr.so",
              "libGL.so",
              "libGLX.so",
              "libOpenGL.so",
              "libGLESv1_CM.so",
              "libGLESv2.so",
              "libEGL.so",
              "libGLdispatch.so",
              "libGLX_nvidia.so",
              "libEGL_nvidia.so",
              "libGLESv2_nvidia.so",
              "libGLESv1_CM_nvidia.so",
              "libnvidia-eglcore.so",
              "libnvidia-egl-wayland.so",
              "libnvidia-glcore.so",
              "libnvidia-tls.so",
              "libnvidia-glsi.so",
              "libnvidia-opticalflow.so"
            ]
          }
        }
      ]
    }

  volume.conf.old: |-
    {
      "volume": [
      {{- $binaries := list "gpu-client" }}
      {{- $libraries := list "libcuda-control.so" }}
      {{- range $index, $package := .Values.nvidia.packages }}
        {{- if $package.installed }}
          {{- if $package.binaries }}
            {{- range $index, $binary := $package.binaries -}}
              {{- $binaries = append $binaries $binary }}
            {{- end }}
          {{- end }}
          {{- if $package.libraries }}
            {{- range $index, $library := $package.libraries -}}
              {{- $libraries = append $libraries $library }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
        {
          "name": "nvidia",
          "base": "/etc/gpu-manager/vdriver",
          "mode": "ro",
          "components": {
            "binaries": {{ $binaries | toPrettyJson | indent 12 | trim }},
            "libraries": {{ $libraries | toPrettyJson | indent 12 | trim }}
          }
        },
      {{- $binaries := list }}
      {{- $libraries := list }}
      {{- range $index, $package := .Values.nvidia.packages }}
        {{- if $package.installed }}
          {{- if $package.binaries }}
            {{- range $index, $binary := $package.binaries -}}
              {{- $binaries = append $binaries $binary }}
            {{- end }}
          {{- end }}
          {{- if $package.libraries }}
            {{- range $index, $library := $package.libraries -}}
              {{- $libraries = append $libraries $library }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
        {
          "name": "origin",
          "base": "/etc/gpu-manager/vdriver",
          "mode": "ro",
          "components": {
            "binaries": {{ $binaries | toPrettyJson | indent 12 | trim }},
            "libraries": {{ $libraries | toPrettyJson | indent 12 | trim }}
          }
        }
      ]
    }
{{- if .Values.config }}
  extra-config.json: {{ .Values.config | toJson | quote }}
{{- else }}
  extra-config.json: "{}"
{{- end }}
